import { Component, OnInit } from '@angular/core';
import { AfterViewInit, ElementRef, } from '@angular/core';
import { DataService } from '../data.service';
@Component({
  selector: 'app-homepage-full',
  templateUrl: './homepage-full.page.html',
  styleUrls: ['./homepage-full.page.scss'],
})
export class HomepageFullPage implements OnInit {
  public ind:any=[


  ]
  public allProducts:any=[
    {
      img:'../../assets/icon/colv.png',
      name:'Cloves',
      nameurdu:'لونگ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/ilachi.png',
      name:'Cardamom',
      nameurdu:'الائچی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/hot.png',
      name:'Spices',
      nameurdu:'گرم مصالحہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/star.png',
      name:'S Anise',
      nameurdu:'بادیاں خطائی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/bg.png',
      name:'Bl.. papar ',
      nameurdu:'کالی مرچ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/white.png',
      name:' Wh.. Papar   ',
      nameurdu:'سفید مرچ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/bppowder.png',
      name:' Bl.. Pepper Powder   ',
      nameurdu:'کالی مرچ  پاؤڈر',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/wpblackpowder.png',
      name:' W.. Pepper Powder ',
      nameurdu:'سفید مرچ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/masalpowder.png',
      name:'Spices Powder ',
      nameurdu:' مصالحہ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sinaspowder.png',
      name:'Cinnamon Powder',
      nameurdu:' دار چینی پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/Cinnamon.png',
      name:'Cinnamon',
      nameurdu:' دار چینی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/blackcardamom.png',
      name:'Cardamom',
      nameurdu:'بڑی الائچی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/jafel.png',
      name:'Nutmeg',
      nameurdu:'جائفل ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/jalwatri.png',
      name:'Jalwatri',
      nameurdu:'جلوتری ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/zerraa.png',
      name:'Cumin',
      nameurdu:'انڈین زیرہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/teezpta.png',
      name:'Bay Leaf',
      nameurdu:'  تیزپتہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/zerraa.png',
      name:'Cumin',
      nameurdu:' ایرانی زیرہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/fannel.png',
      name:'Fennel',
      nameurdu:' سونف ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/dayneya.png',
      name:'Coriander',
      nameurdu:' خشک دھنیا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/ajwann.png',
      name:'Celery',
      nameurdu:' اجوائن ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chilka.png',
      name:'Psyllium husk',
      nameurdu:' چھلکا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/methi.png',
      name:'Dried Fenugreek',
      nameurdu:' خشک میتھی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khaskas.png',
      name:'Poppy Seeds',
      nameurdu:' خشخاش ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/metha soda.png',
      name:'Ba.. Soda',
      nameurdu:' میٹھا سوڈا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/kala.png',
      name:'Black Salt',
      nameurdu:'کالا نمک ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chat msala.png',
      name:' spice',
      nameurdu:'چاٹ مصالحہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sabu.png',
      name:'Tapioca',
      nameurdu:'ساگو دانہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/anrdana.png',
      name:'Pomegranate',
      nameurdu:'اناردانہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sabtbdam.png',
      name:'Almonds',
      nameurdu:'بادام',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/akhrot.png',
      name:'Walnut',
      nameurdu:'اخروٹ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/badam.png',
      name:'Almonds',
      nameurdu:' بادام گیری',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/cajo.png',
      name:'Cashews',
      nameurdu:' کاجو',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/pist.png',
      name:'Pistachios',
      nameurdu:' پستہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chalgoze.png',
      name:'Pine nut',
      nameurdu:'چلغوزہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/inger.png',
      name:'Figs',
      nameurdu:' انجیر',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/magaz.png',
      name:'Melon Seed',
      nameurdu:' چار مغز',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/mix dry.png',
      name:'Mix dry fruits', 
      nameurdu:' میوہ جات',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khajoor.png',
      name:'Dates',
      nameurdu:'ایرانی کھجور',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/soji.png',
      name:'Raisins',
      nameurdu:'کشمش',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khopa.png',
      name:'Dried Coconut',
      nameurdu:'گری',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/garibrada.png',
      name:'Co.. Powder',
      nameurdu:'گری برادا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/alobkhara.png',
      name:'Dried Plum',
      nameurdu:'آلو بخارا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/imli.png',
      name:'Tamarind',
      nameurdu:'املی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
  ]
  public dryFruits:any=[
    {
      img:'../../assets/icon/anrdana.png',
      name:'Pomegranate',
      nameurdu:'اناردانہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sabtbdam.png',
      name:'Almonds',
      nameurdu:'بادام',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/akhrot.png',
      name:'Walnut',
      nameurdu:'اخروٹ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/badam.png',
      name:'Almonds',
      nameurdu:' بادام گیری',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/cajo.png',
      name:'Cashews',
      nameurdu:' کاجو',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/pist.png',
      name:'Pistachios',
      nameurdu:' پستہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chalgoze.png',
      name:'Pine nut',
      nameurdu:'چلغوزہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/inger.png',
      name:'Figs',
      nameurdu:' انجیر',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khob.png',
      name:'Dried Apricot ',
      nameurdu:' خشک خوبانی',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    
    {
      img:'../../assets/icon/magaz.png',
      name:'Melon Seed',
      nameurdu:' چار مغز',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khajoor.png',
      name:'Dates',
      nameurdu:'ایرانی کھجور',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/soji.png',
      name:'Raisins',
      nameurdu:'کشمش',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khopa.png',
      name:'Dried Coconut',
      nameurdu:'گری',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/garibrada.png',
      name:'Co.. Powder',
      nameurdu:'گری برادا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/alobkhara.png',
      name:'Dried Plum',
      nameurdu:'آلو بخارا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/imli.png',
      name:'Tamarind',
      nameurdu:'املی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
  ]
  public spices:any=[
    {
      img:'../../assets/icon/colv.png',
      name:'Cloves',
      nameurdu:'لونگ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/ilachi.png',
      name:'Cardamom',
      nameurdu:'الائچی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/hot.png',
      name:'Spices',
      nameurdu:'گرم مصالحہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/star.png',
      name:'S Anise',
      nameurdu:'بادیاں خطائی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/bg.png',
      name:'Bl.. papar ',
      nameurdu:'کالی مرچ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/white.png',
      name:' Wh.. Papar   ',
      nameurdu:'سفید مرچ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/bppowder.png',
      name:' Bl.. Pepper Powder   ',
      nameurdu:'کالی مرچ  پاؤڈر',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/wpblackpowder.png',
      name:' W.. Pepper Powder ',
      nameurdu:'سفید مرچ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/masalpowder.png',
      name:'Spices Powder ',
      nameurdu:' مصالحہ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sinaspowder.png',
      name:'Cinnamon Powder',
      nameurdu:' دار چینی پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/Cinnamon.png',
      name:'Cinnamon',
      nameurdu:' دار چینی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/blackcardamom.png',
      name:'Cardamom',
      nameurdu:'بڑی الائچی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/jafel.png',
      name:'Nutmeg',
      nameurdu:'جائفل ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/jalwatri.png',
      name:'Jalwatri',
      nameurdu:'جلوتری ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/zerraa.png',
      name:'Cumin',
      nameurdu:'انڈین زیرہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/teezpta.png',
      name:'Bay Leaf',
      nameurdu:'  تیزپتہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/zerraa.png',
      name:'Cumin',
      nameurdu:' ایرانی زیرہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/fannel.png',
      name:'Fennel',
      nameurdu:' سونف ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/dayneya.png',
      name:'Coriander',
      nameurdu:' خشک دھنیا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/ajwann.png',
      name:'Celery',
      nameurdu:' اجوائن ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chilka.png',
      name:'Psyllium husk',
      nameurdu:' چھلکا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/methi.png',
      name:'Dried Fenugreek',
      nameurdu:' خشک میتھی ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/khaskas.png',
      name:'Poppy Seeds',
      nameurdu:' خشخاش ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/metha soda.png',
      name:'Ba.. Soda',
      nameurdu:' میٹھا سوڈا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/kala.png',
      name:'Black Salt',
      nameurdu:'کالا نمک ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chat msala.png',
      name:' spice',
      nameurdu:'چاٹ مصالحہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sabu.png',
      name:'Tapioca',
      nameurdu:'ساگو دانہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
  ]
  public mixDry:any=[
    {
      img:'../../assets/icon/mix dry.png',
      name:'Mix dry',
      nameurdu:'کشمش',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },

  ]
  public nuts:any=[
    {
      img:'../../assets/icon/sabtbdam.png',
      name:'Almonds',
      nameurdu:'بادام',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/akhrot.png',
      name:'Walnut',
      nameurdu:'اخروٹ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/badam.png',
      name:'Almonds',
      nameurdu:' بادام گیری',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/cajo.png',
      name:'Cashews',
      nameurdu:' کاجو',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/pist.png',
      name:'Pistachios',
      nameurdu:' پستہ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chalgoze.png',
      name:'Pine nut',
      nameurdu:'چلغوزہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/magaz.png',
      name:'Melon Seed',
      nameurdu:' چار مغز',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },

  ]
  public powdered:any=[
    {
      img:'../../assets/icon/bppowder.png',
      name:' Bl.. Pepper Powder   ',
      nameurdu:'کالی مرچ  پاؤڈر',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/wpblackpowder.png',
      name:' W.. Pepper Powder ',
      nameurdu:'سفید مرچ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/masalpowder.png',
      name:'Spices Powder ',
      nameurdu:' مصالحہ پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/sinaspowder.png',
      name:'Cinnamon Powder',
      nameurdu:' دار چینی پاؤڈر ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/metha soda.png',
      name:'Ba.. Soda',
      nameurdu:' میٹھا سوڈا ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/kala.png',
      name:'Black Salt',
      nameurdu:'کالا نمک ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
    {
      img:'../../assets/icon/chat msala.png',
      name:' spice',
      nameurdu:'چاٹ مصالحہ ',
      weght:' 100',
      price:'900',
      icon:'heart-outline',
    },
  ]
  private lastScrollTop = 0; // Track last scroll position

  constructor(private elementRef: ElementRef, private dataService: DataService) {}

 
  
  ngOnInit() {
    this.ind= this.dataService.getind();
  }
  filteredProducts = [...this.allProducts]; // Initially show all products

  // Function to filter products based on category
  showProducts(category: string) {
    if (category === 'all') {
      this.filteredProducts = [...this.allProducts];
    } else if (category === 'dryFruits') {
      this.filteredProducts = [...this.dryFruits];
    } else if (category === 'spices') {
      this.filteredProducts = [...this.spices];
    } else if (category === 'mixDry') {
      this.filteredProducts = [...this.mixDry];
    } else if (category === 'nuts') {
      this.filteredProducts = [...this.nuts];
    } else if (category === 'powdered') {
      this.filteredProducts = [...this.powdered];
    }
}
}
